version: '3.7'
name: laravel_docker
networks:
    net:
        driver: bridge
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        container_name: ld_server
        ports:
            - ${SERVER_PORT}:80
        volumes:
            - ../:/var/www/html
            - /var/www/html/docker/data
            - /var/www/html/node_modules
        links:
            - mysql
        depends_on:
            - mysql
            - redis
        networks:
            - net
        environment:
            DB_HOST: mysql
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            SERVER_PORT: ${SERVER_PORT}
    vite:
        build:
            context: ./vite
            dockerfile: Dockerfile
        image: vite
        container_name: ld_vite
        networks:
            - net
        ports:
            - ${VITE_PORT}:5173
        command: |
            bash -c "source ~/.nvm/nvm.sh &&
            npm i && npm run dev -- --host 0.0.0.0"
        volumes:
            - ../:/var/www/html
            - /var/www/html/docker/data
            - /var/www/html/vendor
    mysql:
        platform: linux/x86_64
        image: mysql:8
        container_name: ld_mysql
        networks:
            - net
        command: --max_allowed_packet=92505856 --ssl=0
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data:/data
    redis:
        image: redis:6
        container_name: ld_redis
        networks:
            - net
        volumes:
            - ./data/redis:/data/redis
        ports:
            - ${REDIS_PORT}:6379
    smtp:
        image: dockage/mailcatcher:0.9.0
        container_name: ld_smtp
        ports:
            - ${SMTP_PORT}:1025
            - ${SMTP_GUI_PORT}:1080
        networks:
            - net
    s3mock:
        image: adobe/s3mock
        container_name: ld_s3
        networks:
            - net
        environment:
            - initialBuckets=laravel_docker
            - debug=true
        ports:
            - ${S3_PORT}:9090
